services:
  crossgame-db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: 'America/Santiago'
      PGTZ: 'America/Santiago'
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: crossgame-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  principal_app:
    build: .
    ports:
      - "4000:4000"
      - "4010:4010"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - crossgame-db
    links:
      - crossgame-db